# Generated by Django 5.0.3 on 2024-03-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='liga_robo',
            new_name='ligaRobo',
        ),
        migrations.RenameField(
            model_name='dados',
            old_name='reset_contador',
            new_name='resetContador',
        ),
        migrations.RenameField(
            model_name='dados',
            old_name='valor_contagem',
            new_name='valorContagem',
        ),
    ]
